---
- name: Remove dnsmasq conf file
  file:
    name: /etc/NetworkManager/dnsmasq.d/{{ cluster_name }}.{{ domain }}
    state: absent
  register: result

- name: Get dnsmasq child process
  shell: "systemctl status NetworkManager | grep /usr/sbin/dnsmasq | awk '{print$2}'"
  register: nm_dnsmasq_cmd
  when: result.changed

- name: Restart dnsmasq child process
  shell: 'kill {{ nm_dnsmasq_cmd.stdout }}'
  when: result.changed
